/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimeRecentPlayedCard: typeof import('./src/components/card/AnimeRecentPlayedCard.vue')['default']
    Background: typeof import('./src/components/background/Background.vue')['default']
    BilibiliMusicCard: typeof import('./src/components/card/BilibiliMusicCard.vue')['default']
    CardLoading: typeof import('./src/components/card/CardLoading.vue')['default']
    CardTemplate: typeof import('./src/components/card/CardTemplate.vue')['default']
    Dots: typeof import('./src/components/background/Dots.vue')['default']
    GamesRecentPlayedCard: typeof import('./src/components/card/GamesRecentPlayedCard.vue')['default']
    GithubHeatmapCard: typeof import('./src/components/card/GithubHeatmapCard.vue')['default']
    GithubLanguageBarCard: typeof import('./src/components/card/GithubLanguageBarCard.vue')['default']
    ListFavorites: typeof import('./src/components/ListFavorites.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    ListProjects: typeof import('./src/components/ListProjects.vue')['default']
    Particle: typeof import('./src/components/background/Particle.vue')['default']
    PhotoGallery: typeof import('./src/components/PhotoGallery.vue')['default']
    Plum: typeof import('./src/components/background/Plum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongsRecentPlayedCard: typeof import('./src/components/card/SongsRecentPlayedCard.vue')['default']
    Stars: typeof import('./src/components/background/Stars.vue')['default']
    TheBack: typeof import('./src/components/layout/TheBack.vue')['default']
    TheFooter: typeof import('./src/components/layout/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layout/TheHeader.vue')['default']
    TheToTop: typeof import('./src/components/layout/TheToTop.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
  }
}
